# This file was generated by GoReleaser. DO NOT EDIT.
cask "jentic" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "9d8fb35dd12ed07e6b0dc6576f179510a58c8a003f6d01a5360ec9caaa53d92a"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f09c69cf0712721f226656f894834a0ef1b49ac86f4305138d2303c942f31348"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e4b6ef8ba12a71cde8533ebb8a0d09290193d95cbba0a8149ee076746551b9d"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "48452417d2ceab38fc2c805d6195f773fb626e6332194585554707e21d0df1bc"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jentic"
  desc "Jentic One CLIs — jenticctl (installer/lifecycle) + jentic (API client)"
  homepage "https://jentic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jenticctl"
  binary "jentic"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jenticctl"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jentic"]
    end
  end

  # No zap stanza required

end
