# This file was generated by GoReleaser. DO NOT EDIT.
cask "jentic" do
  version "0.36.0"

  on_macos do
    on_arm do
      sha256 "65d41b8c33d3bfa66bb4e14c4c87297c9176cc61f18a1c2ed12e211c7b445be6"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bafeb7e4fd74d92afa9ef59f85f104a3ea18772149aba8c6e9c3c49f2422a3b9"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9a31a92311f83b50c1b95ce43d0281ac0f55c9a1d935ecd462f7cd06d751ad24"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fb903f70430d01ff6f1b9ae5ab13db1032b01f35aeb87207354798d27518072e"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jentic"
  desc "Jentic One CLIs — jenticctl (installer/lifecycle) + jentic (API client)"
  homepage "https://jentic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jenticctl"
  binary "jentic"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jenticctl"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jentic"]
    end
  end

  # No zap stanza required
end
