# This file was generated by GoReleaser. DO NOT EDIT.
cask "jentic" do
  version "0.15.3"

  on_macos do
    on_intel do
      sha256 "0e954174485d2b0b253d75f7b722260daee7822cb5389258c4633c40fc02aedc"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3dc2908b1861b91d5aed251a3a2c5dfcb97df8ce66da776444a253ebffbd115c"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aed3c9160d7dc0f34a265a5685c628e12c37d29a18ed00e0027b5aa9846d2290"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "25d8b0b4c56dfab3e2c887c771743f9bfbcd86fbc3f8b397c46eb105529b74ba"
      url "https://github.com/jentic/jentic-one/releases/download/v#{version}/jentic-one_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jentic"
  desc "Jentic One CLIs — jenticctl (installer/lifecycle) + jentic (API client)"
  homepage "https://jentic.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jenticctl"
  binary "jentic"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jenticctl"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jentic"]
    end
  end

  # No zap stanza required

end
